# Generated by Django 5.1.7 on 2025-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="is_available",
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, verbose_name="Доступен для покупки"
            ),
        ),
    ]
