# Generated by Django 5.1.7 on 2025-03-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_remove_lesson_is_available_product_is_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course",
            new_name="product",
        ),
    ]
